### ISSUE TITLE
Conditional usage in Apollo Server

### ISSUE THREAD

**Issue by KATT** [gajus/graphql-deduplicator#13]
Any idea how I could use `graphql-deduplicator` conditionally in Apollo Server?

`ApolloServer:formatResponse` doesn't support access to the request object (or context) so I tried by doing a `GraphQLExtension` like this:

```typescript

class DeduplicateResponseExtension extends GraphQLExtension<Context> {
  public willSendResponse(o: {
    graphqlResponse: GraphQLResponse;
    context: Context;
  }): { graphqlResponse: GraphQLResponse; context: Context } {
    const { context, graphqlResponse } = o
    if (context.req.query.deduplicate && graphqlResponse.data && !graphqlResponse.data.__schema) {
      const newResponse = deflate(graphqlResponse)
      return {
        ...o,
        graphqlResponse: newResponse,
      }
    }

    return o
  }
}
```

However, when using it I receive an error from Apollo Server:

```json
{
  "error": {
    "errors": [
      {
        "message": "response.http.headers is not iterable",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "TypeError: response.http.headers is not iterable",
              "    at [..]/node_modules/apollo-server-core/dist/runHttpQuery.js:164:55",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled ([..]/node_modules/apollo-server-core/dist/runHttpQuery.js:4:54)"
            ]
          }
        }
      }
    ]
  }
}
```

This issue might belong in apollo-server, asking here first to see if anyone knows of a setup that works with Apollo Server.

**Comment by KATT** [comment]
Digging a bit it seems like `graphqlResponse` contains a `http` property that `graphql-deduplicator` type of.. gonna see if I can fix it.

**Comment by KATT** [comment]
@gajus if you can publish a new release I'll confirm that it works + do a PR with Apollo Server setup instructions
